# Generated by Django 5.2.7 on 2025-10-13 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("oa", "Online Assessment"),
                            ("interview", "Interview"),
                            ("offered", "Offered"),
                            ("rejected", "Rejected"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="job",
            name="application_status_2cfdeb_idx",
        ),
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.RemoveField(
            model_name="job",
            name="status",
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="applications.job",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["user", "status"], name="application_user_id_55b4e4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("user", "job")},
        ),
    ]
