# Generated by Django 5.2.7 on 2025-11-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_job_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="deadline_at",
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[("full_time", "Full Time"), ("intern", "Intern")],
                default="full_time",
                max_length=20,
            ),
        ),
    ]
