# Generated by Django 4.2.26 on 2025-11-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_remove_application_deadline_at_alter_job_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="website",
        ),
        migrations.AddField(
            model_name="job",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
