# Generated by Django 4.2.26 on 2025-12-08 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeetCodeProblem",
            fields=[
                ("problem_id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("Easy", "Easy"), ("Medium", "Medium"), ("Hard", "Hard")],
                        max_length=10,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProblemRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_records",
                        to="leetcode.leetcodeproblem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leetcode_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "problem")},
            },
        ),
    ]
